<a href="https://colab.research.google.com/github/ean0418/ean0418/blob/main/Jul31_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 함수

# 하나의 array에 적용 (단항 유니버셜함수)

유니버셜함수 : ndarray안에 있는 데이터의 요소별로 연산을 수행해주는 함수


In [1]:
import numpy as np

ar1 = np.random.randn(5, 3)
ar1

array([[-0.79733021,  1.18005556, -0.35922661],
       [-0.22568841, -1.59960253, -0.31937606],
       [ 2.00919469,  1.43206159, -0.17651588],
       [-1.13679414, -1.63050761, -1.59754078],
       [ 0.23865702, -0.3732531 ,  0.22276472]])

In [2]:
# 각 요소의 절대값
np.abs(ar1)

array([[0.79733021, 1.18005556, 0.35922661],
       [0.22568841, 1.59960253, 0.31937606],
       [2.00919469, 1.43206159, 0.17651588],
       [1.13679414, 1.63050761, 1.59754078],
       [0.23865702, 0.3732531 , 0.22276472]])

In [3]:
# 각 요소의 제곱근 계산 ( == ar1 ** 0.5)
np.sqrt(ar1)

<ipython-input-3-a9f5646fce59>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(ar1)


array([[       nan, 1.08630362,        nan],
       [       nan,        nan,        nan],
       [1.41746065, 1.19668776,        nan],
       [       nan,        nan,        nan],
       [0.48852535,        nan, 0.47197957]])

In [4]:
# 각 요소의 제곱 계산
np.square(ar1)

array([[0.63573547, 1.39253112, 0.12904376],
       [0.05093526, 2.55872827, 0.10200107],
       [4.0368633 , 2.0508004 , 0.03115786],
       [1.29230091, 2.65855507, 2.55213653],
       [0.05695717, 0.13931788, 0.04962412]])

In [5]:
# 각 요소를 자연로그, 상용로그, 아래가 2인 로그를 씌운 값 계산
print(np.log(ar1))
print(np.log10(ar1))
print(np.log2(ar1))

[[        nan  0.16556152         nan]
 [        nan         nan         nan]
 [ 0.69773399  0.35911508         nan]
 [        nan         nan         nan]
 [-1.43272782         nan -1.50163914]]
[[        nan  0.07190245         nan]
 [        nan         nan         nan]
 [ 0.30302202  0.1559617          nan]
 [        nan         nan         nan]
 [-0.62222578         nan -0.65215359]]
[[        nan  0.23885478         nan]
 [        nan         nan         nan]
 [ 1.00661737  0.51809354         nan]
 [        nan         nan         nan]
 [-2.06698932         nan -2.16640734]]


<ipython-input-5-2efbfdc3f05d>:2: RuntimeWarning: invalid value encountered in log
  print(np.log(ar1))
<ipython-input-5-2efbfdc3f05d>:3: RuntimeWarning: invalid value encountered in log10
  print(np.log10(ar1))
<ipython-input-5-2efbfdc3f05d>:4: RuntimeWarning: invalid value encountered in log2
  print(np.log2(ar1))


In [7]:
# 각 요소의 부호 나타내기 (+ : 1, - : -1, 0 : 0)
np.sign(ar1)

array([[-1.,  1., -1.],
       [-1., -1., -1.],
       [ 1.,  1., -1.],
       [-1., -1., -1.],
       [ 1., -1.,  1.]])

In [8]:
# 각 요소의 소수 첫번째 자리에서 올림한 값 계산
np.ceil(ar1)

array([[-0.,  2., -0.],
       [-0., -1., -0.],
       [ 3.,  2., -0.],
       [-1., -1., -1.],
       [ 1., -0.,  1.]])

In [9]:
# 각 요소의 소수 첫번째 자리에서 버림한 값 계산
np.floor(ar1)

array([[-1.,  1., -1.],
       [-1., -2., -1.],
       [ 2.,  1., -1.],
       [-2., -2., -2.],
       [ 0., -1.,  0.]])

In [10]:
# 각 요소의 소수 첫번째 자리에서 올림한 값 계산
np.round(ar1)

array([[-1.,  1., -0.],
       [-0., -2., -0.],
       [ 2.,  1., -0.],
       [-1., -2., -2.],
       [ 0., -0.,  0.]])

In [11]:
# 각 요소가 nan인 경우 True, 아닌 경우 False를 반환
np.isnan(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [12]:
# 각 요소가 무한대인 경우 True, 아닌 경우 False를 반환
np.isinf(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [14]:
# 각 요소에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)
# ~h : 쌍곡선 함수
# 쌍곡선 : 고정된 두 초점으로부터 거리가 일정한 점들에 의해 나타나는 곡선

np.cos(ar1)
np.cosh(ar1)
np.sin(ar1)
np.sinh(ar1)
np.tan(ar1)
np.tanh(ar1)

array([[-0.66254156,  0.82746913, -0.34453263],
       [-0.22193307, -0.9216087 , -0.30894264],
       [ 0.96467147,  0.89208831, -0.17470516],
       [-0.81333176, -0.92613384, -0.92129753],
       [ 0.23422685, -0.35683389,  0.21915159]])

# 두 개의 array에 적용 (이항 유니버셜함수)

In [15]:
ar1

array([[-0.79733021,  1.18005556, -0.35922661],
       [-0.22568841, -1.59960253, -0.31937606],
       [ 2.00919469,  1.43206159, -0.17651588],
       [-1.13679414, -1.63050761, -1.59754078],
       [ 0.23865702, -0.3732531 ,  0.22276472]])

In [16]:
ar2 = np.random.randn(5, 3)
ar2

array([[-0.27892244,  0.42354332, -0.65140143],
       [ 1.91632922,  0.12653471,  1.1385513 ],
       [ 0.037859  , -0.44509017, -1.37114179],
       [-0.24078744, -0.151013  , -1.15209374],
       [ 0.02494364,  2.37548873,  0.69168108]])

In [17]:
# 두 개의 array에 대해 동일한 위치 요소끼리
# 연산 값을 계산함수 (add, subtract, multiply, divide)
np.multiply(ar1, ar2)
np.subtract(ar1, ar2)
np.add(ar1, ar2)
np.divide(ar1, ar2)

array([[  2.85860908,   2.78615082,   0.55146735],
       [ -0.11777121, -12.64161044,  -0.28051091],
       [ 53.07045795,  -3.21746396,   0.12873642],
       [  4.72115209,  10.79713384,   1.38664131],
       [  9.5678521 ,  -0.15712687,   0.32206276]])

In [18]:
# 두 개의 array에 대해 동일한 위치의 요소끼리 비교해서 최대값 or 최소값 계산
# (maximum, minimum)
np.maximum(ar1, ar2)
np.minimum(ar1, ar2)

array([[-0.79733021,  0.42354332, -0.65140143],
       [-0.22568841, -1.59960253, -0.31937606],
       [ 0.037859  , -0.44509017, -1.37114179],
       [-1.13679414, -1.63050761, -1.59754078],
       [ 0.02494364, -0.3732531 ,  0.22276472]])

# 통계 함수

통계 함수를 통해서 array의 합이나 평균 등을 구할 때

추가로 'axis'라는 파라미터에 대한 값을 지정해서 열 또는 행의 합 또는 평균 등을 구할 수 있음!

In [20]:
# 열 간의 합을 계산
np.sum(ar1  , axis = 0)

array([ 0.08803895, -0.9912461 , -2.22989461])

In [21]:
# 행 간의 합을 계산
np.sum(ar1, axis=1)

array([ 0.02349873, -2.144667  ,  3.2647404 , -4.36484252,  0.08816863])

In [22]:
# 전체 요소의 평균을 계산
np.mean(ar1)

-0.20887345075045827

In [24]:
# 전체 요소의 표준편차, 분산, 최소값, 최대값(std, var, min, max)
# 표준편차 : 데이터가 평균으로부터 얼마나 흩어있는지를 나타내는 지표
# 분산 : 데이터가 평균으로부터 얼마나 멀리 떨어져있는지를 측정하는 지표
np.std(ar1), np.var(ar1), np.min(ar1), np.max(ar1)

(1.0671540467331828,
 1.138817759459008,
 -1.6305076099595248,
 2.0091946893701333)

In [25]:
# 전체 요소의 최솟값, 최대값이 위치한 인덱스의 위치를 반환(argmin, argmax)
np.argmin(ar1), np.argmax(ar1)

(10, 6)

In [26]:
# 맨 처음 요소부터 각 요소까지의 누적합 or 누적곱을 계산(cumsum, cumprod)
np.cumsum(ar1), np.cumprod(ar1)

(array([-0.79733021,  0.38272535,  0.02349873, -0.20218968, -1.80179221,
        -2.12116827, -0.11197358,  1.32008801,  1.14357213,  0.00677799,
        -1.62372962, -3.2212704 , -2.98261337, -3.35586648, -3.13310176]),
 array([-0.79733021, -0.94089395,  0.33799415, -0.07628136,  0.12201986,
        -0.03897022, -0.07829876, -0.11212865,  0.01979249, -0.02249998,
         0.0366864 , -0.05860801, -0.01398721,  0.00522077,  0.001163  ]))

In [29]:
# 사분위수 : 사분위수는 데이터를 4등분한 것
# 25% : 1사분위수, 50% : 2사분위수(중앙값), 75% : 3사분위수
np.quantile(ar1, [0.25, 0.5, 0.75])

array([-0.96706217, -0.31937606,  0.23071087])

In [30]:
# 전체 요소에 대해서 오름차순 정렬
np.sort(ar1)

array([[-0.79733021, -0.35922661,  1.18005556],
       [-1.59960253, -0.31937606, -0.22568841],
       [-0.17651588,  1.43206159,  2.00919469],
       [-1.63050761, -1.59754078, -1.13679414],
       [-0.3732531 ,  0.22276472,  0.23865702]])

In [31]:
# 열 방향으로 오름차순 정렬
np.sort(ar1, axis=0)

array([[-1.13679414, -1.63050761, -1.59754078],
       [-0.79733021, -1.59960253, -0.35922661],
       [-0.22568841, -0.3732531 , -0.31937606],
       [ 0.23865702,  1.18005556, -0.17651588],
       [ 2.00919469,  1.43206159,  0.22276472]])

In [32]:
# zip 함수
# 각 객체들을 파라미터로 받고, 그 요소들을 tuple의 형태로 반환
numbers = [1, 2, 3]
letters = ['A', 'B', 'C']
for pair in zip(numbers, letters):
    print(pair)

(1, 'A')
(2, 'B')
(3, 'C')
